### ISSUE TITLE
no such file to load -- tcltklib (LoadError) upon running "glimmer samples"

### ISSUE THREAD

**Issue by rubyFeedback** [AndyObtiva/glimmer-dsl-swt#16]
org/jruby/RubyKernel.java:1017:in `require': no such file to load -- tcltklib (LoadError)
	from /home/Programs/Jruby/9.3.2.0/lib/ruby/2.6/site_ruby/rubygems/core_ext/kernel_require.rb:85:in `require'
	from /root/.gem/gems/tk-0.4.0/lib/tk.rb:7:in `<main>'
	from org/jruby/RubyKernel.java:1017:in `require'

I first did the gem install command you showed in the main README, and I can launch
the meta-sample example fine. \o/

But when I select an entry and then click "Launch", a window is opened with that error.

"jgem install tk" also fails, not sure why; the regular tk + ruby-tk works on my system.

The output for jgem install tk is:

"check functions.checking for ruby_native_thread_p() in ruby.h... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options."

But that seems bogus because ruby-tk works without jruby fine. I just tested it,
the hello world ruby-tk works. mkmf.log does not contain any useful information.

Anyway - I wanted to mention that error because perhaps glimmer-dsl-swt can
work otherwise. Actually can we have a variant without tk? In the launcher it
may then be useful perhaps to add a combo-box entry where users can
select what GUI variant to use instead. I was a bit surprised when I ran
the example and a tk error showed up. I kind of thought I would be using
the Eclipse SWT library - perhaps I did something wrong. Either way this
is just a bit information, perhaps the README could clarify this a bit.

The "jgem install glimmer-dsl-swt" part worked fine; the only thing that is
perhaps missing is the "what to do next". I then ran "glimmer samples"
and the window showed up too, so something DOES work; just the
part after "Launch" did not work for me, and I can not get jgem to
install tk ... hmm.

Anyway here is a screenshot of this on my poor man's IceWM :)
perhaps this is more useful to you.

https://i.imgur.com/1I6WYtp.png

(On a side note, I think the launcher GUI could perhaps be improved
a tiny bit, a bit more padding between the label and the radio-box 
perhaps, and double-click events for launching the selection but
anyway, this is not the important part, the more important part is
about that error and ruby-tk as seen on the window on the ~
bottom right of that screenshot. I wanted to report that at the least
so it is known. As always please feel to disregard/close at any 
moment in time, this is really just meant as a notification/info.)

**Comment by AndyObtiva** [comment]
I think you got libraries mixed up. You are running tcl/tk in JRUBY?!! [Glimmer DSL for Tk](https://github.com/AndyObtiva/glimmer-dsl-tk) is first of all a different toolkit from Glimmer DSL for SWT, and it is a CRuby toolkit, not a JRuby one. I think that might be your only issue here. Do not use Tk from JRuby as it is not a JRuby toolkit, yet a CRuby one. You can use it from standard Ruby following the instructions on the [Glimmer DSL for Tk](https://github.com/AndyObtiva/glimmer-dsl-tk) page (not Glimmer DSL for SWT).
