### ISSUE TITLE
Snake example for glimmer-dsl-swt?

### ISSUE THREAD

**Issue by rubyFeedback** [AndyObtiva/glimmer-dsl-swt#17]
Hello Andy,

Sorry for stalking you with little proposals. :D

Could you add a snake example (the game) for glimmer-dsl-swt? It's super low priority
but perhaps it would not take too long to add it, considering some other glimmer-variants 
have it. (Tetris is the game-winner for the glimmer-suite, but snake may come in a 
second! I'd propose to enable everything on all glimmer-variants, but I don't want to
add to the workload, so snake is hopefully not too much work. If it already works then
perhaps it could be mentioned briefly in the README?).

**Comment by AndyObtiva** [comment]
Done in [v4.22.2.2](https://rubygems.org/gems/glimmer-dsl-swt/versions/4.22.2.2):

[Snake Sample](https://github.com/AndyObtiva/glimmer-dsl-swt/blob/master/docs/reference/GLIMMER_SAMPLES.md#snake)

![snake](https://raw.githubusercontent.com/AndyObtiva/glimmer-dsl-swt/master/images/glimmer-snake.png)

![video](https://raw.githubusercontent.com/AndyObtiva/glimmer-dsl-swt/master/images/glimmer-snake.gif)
