### ISSUE TITLE
[Documentation, mostly] Glimmer DSL for SWT Video: Playlist? (Small issue request)

### ISSUE THREAD

**Issue by rubyFeedback** [AndyObtiva/glimmer-dsl-swt#19]
Hey there Andy,

I see you linked in to the videos from the main README e. g. here:

https://andymaleh.blogspot.com/search/label/Tutorial+SWT

If you have some time and it may not be too much effort, would it be possible to add
direct URLs / Links to these? For instance:

    Video 1: URL here
    Video 2: URL here

and so forth? Perhaps a table in the README so that a visitor can quickly click
on these, a bit like a playlist on youtube? You already added a playlist there
https://www.youtube.com/watch?v=Mi5phsSdNAA&list=PLSN9HhZ_0-n741vRa_dL-M81cLbqD_kem 
but I think it may be useful to provide direct links too, for people to quickly find it.
For instance, I found that playlist by first going to your blog, then clicking on
the video, and then in youtube clicking on that playlist collection. So perhaps a
direct link from the github README/repository may be helpful; might find more
people too. Some are lazy and will only click on github and may not go to the
blog because they are so lazy ... :P

Rationale: some of the videos are, I believe, more useful for some visitors than
others. I believe in either Video 2 or 3 you spoke about the mixin-based or
class-based approach for glimmer (e. g. to integrate modules and extend
a glimmer-app; this is probably the use case I will need the most when writing
glimmer applications, so that I can retain some flexibility in my own code, 
e. g. when I would like to tap into glimmer, but also retain the flexibility to
have the same code base work with gtk. Kind of a bit of a hybrid meta DSL
or something. I am buzzword-chaining there ... :D )

Anyway - I believe direct URLs to the videos may be very convenient. Right
now this may not be super-important since there are ~5 videos, but perhaps
at the end of the year there may be +10 videos already, so a quick link/table
may perhaps be useful. Either way glimmer on! \o/

**Comment by AndyObtiva** [comment]
Done!

I added links at the end of the [README](https://github.com/AndyObtiva/glimmer-dsl-swt/blob/master/README.md) and at the [top of each sample](https://github.com/AndyObtiva/glimmer-dsl-swt/blob/master/docs/reference/GLIMMER_SAMPLES.md) that has a video tutorial.

In fact, you can [subscribe to the Glimmer channel](https://www.youtube.com/channel/UC5hzDE23HZXsZLAxYk2UJEw) and get alerted automatically when new videos are uploaded.

As mentioned before, the class-based custom widget approach is only supported in Glimmer DSL for SWT and Glimmer DSL for Opal at the moment. It is not available in Glimmer DSL for GTK and other Glimmer DSLs yet. However, the plan is to include it in all Glimmer GUI DSLs eventually.

Cheers!
