### ISSUE TITLE
Scaffold Issue

### ISSUE THREAD

**Issue by tekanic** [AndyObtiva/glimmer-dsl-swt#31]
- CPU Architecture: 86_64
 - OS Mac: Ventura 13.1
 - Java Version: java 17.0.1 2021-10-19 LTS
 - JRuby Version: jruby-9.3.8.0 (via RVM)
 - Glimmer Libraries/Versions: glimmer (2.7.3)
glimmer-dsl-swt (4.27.0.0)

**No such file or directory error**
When following along with tutorial 35 on Youtube, I get the following error when trying to scaffold the greeter example.

`Please specify --github-username or set github.user in ~/.gitconfig (see http://github.com/blog/180-local-github-config for details). For example: git config --global github.user defunkt
#<Class:0x4b7ab7ab>: No such file or directory - greeter
                   chdir at org/jruby/RubyDir.java:411
                      cd at /Users/mm/.rvm/rubies/jruby-9.3.8.0/lib/ruby/stdlib/fileutils.rb:139
              common_app at /Users/mm/.rvm/gems/jruby-9.3.8.0/gems/glimmer-dsl-swt-4.27.0.0/lib/glimmer/rake_task/scaffold.rb:154
                     app at /Users/mm/.rvm/gems/jruby-9.3.8.0/gems/glimmer-dsl-swt-4.27.0.0/lib/glimmer/rake_task/scaffold.rb:139
                  <main> at /Users/mm/.rvm/gems/jruby-9.3.8.0/gems/glimmer-dsl-swt-4.27.0.0/lib/glimmer/rake_task.rb:120
                 execute at /Users/mm/.rvm/gems/jruby-9.3.8.0/gems/rake-13.0.6/lib/rake/task.rb:279
                    each at org/jruby/RubyArray.java:1865
                 execute at /Users/mm/.rvm/gems/jruby-9.3.8.0/gems/rake-13.0.6/lib/rake/task.rb:279
  invoke_with_call_chain at /Users/mm/.rvm/gems/jruby-9.3.8.0/gems/rake-13.0.6/lib/rake/task.rb:219
             synchronize at org/jruby/ext/monitor/Monitor.java:82
  invoke_with_call_chain at /Users/mm/.rvm/gems/jruby-9.3.8.0/gems/rake-13.0.6/lib/rake/task.rb:199
                  invoke at /Users/mm/.rvm/gems/jruby-9.3.8.0/gems/rake-13.0.6/lib/rake/task.rb:188
                  launch at /Users/mm/.rvm/gems/jruby-9.3.8.0/gems/glimmer-dsl-swt-4.27.0.0/lib/glimmer/launcher.rb:145
      launch_application at /Users/mm/.rvm/gems/jruby-9.3.8.0/gems/glimmer-dsl-swt-4.27.0.0/lib/glimmer/launcher.rb:179
                  launch at /Users/mm/.rvm/gems/jruby-9.3.8.0/gems/glimmer-dsl-swt-4.27.0.0/lib/glimmer/launcher.rb:172
                  <main> at /Users/mm/.rvm/gems/jruby-9.3.8.0/gems/glimmer-dsl-swt-4.27.0.0/bin/glimmer:35
                    load at org/jruby/RubyKernel.java:1052
                  <main> at /Users/mm/.rvm/gems/jruby-9.3.8.0/bin/glimmer:25`

**Comment by AndyObtiva** [comment]
This is correct. Scaffolding assumes you have a GitHub user configured in Git.

You are supposed to follow the provided instructions to get through the error:

> Please specify --github-username or set github.user in ~/.gitconfig (see http://github.com/blog/180-local-github-config for details). For example: git config --global github.user defunkt

In your case, you could run:

```
git config --global github.user tekanic
```

Afterwards, try scaffolding again, and it should work.
